name: Deploy PHP Application to EC2

on:
  push:
    branches:
      - master  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and configure dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Copy deploy.sh to EC2
        run: |
          scp -i ${{ secrets.EC2_PRIVATE_KEY }} -o StrictHostKeyChecking=no deploy.sh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~

      - name: Execute deploy.sh on EC2
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} './deploy.sh'
