name: PHP Application Deployment

on:
  push:
    branches:
      - master # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          sudo apt update
          sudo apt install -y sshpass
          sshpass -p "" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_HOST "sudo apt update && sudo apt install -y apache2 mysql-server php libapache2-mod-php php-mysql && sudo systemctl start apache2 && sudo systemctl start mysql && sudo systemctl enable apache2 && sudo systemctl enable mysql && sudo mysql_secure_installation"
          sshpass -p "" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa -r . $EC2_USERNAME@$EC2_HOST:/var/www/html/
